config/routes.rb
Rails.application.routes.draw do
  # get 'books/index'
  # get 'books/show'
  # get 'books/edit'
  # get 'books/new'
  root to: "books#index"
  resources :books
  resources :categories, except: [:destroy]
  get 'search', to: "books#search"

  get 'ascending', to: "books#sort_ascending" 
  get 'descending', to: "books#sort_descending" 

  get 'sports', to: "books#sports_filter"
  get 'travel', to: "books#travel_filter"
  get 'entertainment', to: "books#entertainment_filter"

  get 'sports_and_travel', to: "books#sports_travel"
  get 'sports_and_entertainment', to: "books#sports_entertainment"
  get 'entertainment_and_travel', to: "books#entertainment_travel"
  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :book_categories
    has_many :categories, through: :book_categories
    has_one_attached :image

end

app/models/book_category.rb
class BookCategory < ApplicationRecord
    belongs_to :book
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :book_categories
    has_many :books, through: :book_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 15}
    validates_uniqueness_of :name

    

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id]) 
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)

    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id]) 
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search
    @query = params[:query]
    @books = Book.joins(:categories).where("categories.name LIKE ?", "%#{@query}%")

  end

  def sports_filter
     
    @books = Book.joins(:categories).where(categories: {name: "sports"})
    render 'index'
  end

  def travel_filter

    @books = Book.joins(:categories).where(categories: {name: "travel"})
    render 'index'
  end

  def entertainment_filter

    # Book.joins(:categories).where(categories: {name: "sports"}, categories: {name: "travel"})  
    @books = Book.joins(:categories).where(categories: {name: "entertainment"})
    render 'index'
  end

  def sports_travel
    @books = Book.joins(:categories).where(categories: {name: "sports"}, categories: {name: "travel"}) 
    render 'index'
  end

  def sports_entertainment
    @books = Book.joins(:categories).where(categories: {name: "sports"}, categories: {name: "entertainment"})
    # @books = Book.includes(:categories).where(categories: {name:"sports"}).and(Book.includes(:categories).where(categories: {name:"entertainment"}))
    render 'index'
  end

  def entertainment_travel
    @books = Book.joins(:categories).where(categories: {name: "entertainment"}, categories: {name: "travel"}) 
    render 'index'
  end
  
  def sort_ascending
    @books = Book.all.order(price: :asc)
    render 'index'
  end

  def sort_descending
    @books = Book.all.order(price: :desc)
    render 'index'
  end

  private
  def book_params
    params.require(:book).permit(:title, :description,:price, :image, category_ids: [])
  end

  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def index 
        @categories = Category.all
    end

    def new 

        @category = Category.new
        
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            flash[:success] = "You have successfully created a new category"
            redirect_to categories_path

        else
            render 'new'
        end 
    end

    def show 
        
    end

    private

    def category_params

        params.require(:category).permit(:name)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb

<div align="center">
<div class="mb-3 col-md-8">
    <%= form_with model: @book do |f|%>
    <%= f.label "Book Title", class:"form-label"%>
    <%= f.text_field :title, placeholder: "Enter book title", class:"form-control"%>
</div>
    <div class="mb-3 col-md-8">
        <%= f.label "Book Description",class:"form-label"%>
        <%= f.text_area :description, placeholder: "Enter book description", class:"form-control"%>
    </div>
    <div class="mb-3 col-md-8">
        <%= f.label "Book Price",class:"form-label"%>
        <%= f.text_field :price, placeholder: "Enter book price", class:"form-control"%>
    </div>

    
    <div class="mb-3 col-md-8">
        <%= f.label "Book Picture",class:"form-label"%>
        <%= f.file_field :image, class:"form-control"%>
    </div>

    <div class = "col-sm-8">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class:"checkbox") + cb.text} %>
        <%end%>

    </div>
    
    <%= f.submit class:"btn btn-primary"%>
    <%end%>
</div>

app/views/books/edit.html.erb
<h1 align = "center">Edit book info</h1>

<%= render "form"%>

app/views/books/index.html.erb
<h1 align = "center">Displaying the Books</h1>

<h4 align = "center"><%= link_to "View all books", books_path,class:"btn btn-success" %>|<%= link_to "Add new Book", new_book_path,class:"btn btn-success"%></h4>


<% @books.each do |book| %>
    
    <div class="row">
        <div class="col">
            <div class="card card-body bg-light">
                
                <div class="article-title bold">
                    <%= image_tag(book.image, style:"width: 100px; border-radius: 50%;") %>
                    Title: <%= link_to book.title, book_path(book) %>

                </div>
                <div class="article-body">
                    Description: <%= truncate(book.description, length: 100)%>
                </div>
                <div class="article-price">
                    Price: $<%= book.price%>
                </div>
            </div>
        </div>
    </div>
    <% if book.categories.any?%>
        <%= render book.categories%>

    <%end%>

    <div class="article-actions margin-left">
        
        <%= button_to "Update", edit_book_path(book), method: 'get',class:"btn btn-primary" %>
        <div class="margin-btn"></div>
        <%= button_to "Delete", book_path(book), method: "delete", data: {confirm:"Are you sure?"}, class:"btn btn-danger"%>
    </div>
    <br>

<%end%>

app/views/books/new.html.erb
<h1 align = "center">Add New Book</h1>

<%= render "form"%>

app/views/books/search.html.erb
<h1> Search results </h1>

<% @books.each do |book| %>
    
    <div class="row">
        <div class="col">
            <div class="card card-body bg-light">
                <div class="article-title bold">

                    Title: <%= link_to book.title, book_path(book) %>

                </div>
                <div class="article-body">
                    Description: <%= truncate(book.description, length: 100)%>
                </div>
                <div class="article-price">
                    Price: $<%= book.price%>
                </div>
            </div>
        </div>
    </div>
    <% if book.categories.any?%>
        <%= render book.categories%>

    <%end%>
    <div class="article-actions margin-left">
        
        <%= button_to "Update", edit_book_path(book), method: 'get',class:"btn btn-primary" %>
        <div class="margin-btn"></div>
        <%= button_to "Delete", book_path(book), method: "delete", data: {confirm:"Are you sure?"}, class:"btn btn-danger"%>
    </div>
    <br>

<%end%>

app/views/books/show.html.erb
<h2 align="center"> Title: <%= @book.title %> </h2>

<div class="card card-body bg-light" align="center">
    <h4> Description: <%= @book.description %> </h4>
    <hr>
    <h4> Image: <%= image_tag(@book.image, style:"width: 100px;") %> </h4>
    <hr>
    <h4> Price: $<%= @book.price %> </h4>
</div>
<% if @book.categories.any? %>
    <p> Categories: <%= render @book.categories %> </p>
<%end%>
<div class="article-actions margin-left">
    <%= link_to "View all books", books_path,class:"btn btn-success" %>
    <div class="margin-btn"></div>
    <%= button_to "Update", edit_book_path(@book), method: 'get',class:"btn btn-primary" %>
    <div class="margin-btn"></div>
    <%= button_to "Delete", book_path(@book), method: "delete", data: {confirm:"Are you sure?"}, class:"btn btn-danger"%>
</div>

app/views/categories/_category.html.erb
<span class="badge">  <%= category.name %> &nbsp; </span>

app/views/categories/index.html.erb
<h1 align="center">Listing all the categories</h1>

<% @categories.each do |category| %>

        <div class="center">
            <div class="card card-body bg-light bold">  
                <%= link_to "#{category.name}", category_path(category)%>
                              
            </div>
        </div>
<%end%>

app/views/categories/new.html.erb
<h1 align ="center">Create new category</h1>

<div align="center">
<div class="mb-3 col-md-8">
    <%= form_with model: @category do |f|%>
    <%= f.label "Category Name", class:"form-label"%>
    <%= f.text_field :name, placeholder: "Enter category name", class:"form-control"%>
</div>
    <%= f.submit class:"btn btn-primary"%>
    <%end%>
</div>

app/views/categories/show.html.erb
<h1>Showing categories</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Book App", books_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Show by categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            <li> <%= link_to "Sports", "sports", class:"dropdown-item"%></li>
            <li> <%= link_to "Travel", "travel", class:"dropdown-item"%></li>
            <li> <%= link_to "Entertainment", "entertainment", class:"dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li> <%= link_to "Sports | Travel", "sports_and_travel", class:"dropdown-item"%></li>
            <li> <%= link_to "Sports | Entertainment", "sports_and_entertainment", class:"dropdown-item"%></li>
            <li> <%= link_to "Entertainment | Travel", "entertainment_and_travel", class:"dropdown-item"%></li>

          </ul>
        </li>
      </ul>

    
      <form method = "GET" action = "/ascending">
        <a name="sort">
        </a>

        <input type="submit" value="Sort_Ascending"/>
      </form>

      |

      <form method = "GET" action = "/descending">
        <a name="sort">
        </a>

        <input type="submit" value="Sort_Descending"/>
      </form>

      |

      <form class="d-flex" method = "GET" action = "/search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name = "query" >
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>